version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d:rw
      - ./config/logs:/var/log/nginx:rw
  ekpa-papadimitriou:
    container_name: ekpa-papadimitriou
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    command: bash -c 'pip3 install -r requirements.txt && ./run.sh'
